spring:
  datasource:
    url: jdbc:mysql://localhost:3306/livraria
    username: docker
    password: docker
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      '[format_sql]': true
