spring:
  datasource:
    url: jdbc:mysql://localhost:3306/livraria
    username: root
    password: docker
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

jwt:
  secret: JWT_SUPER_SECRET
